version: '3'
services:
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - ng-node
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  node:
    build:
      context: node
    networks:
      - ng-node
    volumes:
      - ./node:/usr/src/app
      -  /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

  nginx:
    build:
      context: nginx
    networks:
      - ng-node
    ports:
      - "8080:8080"
    restart: always

networks:
  ng-node:
    driver: bridge